### ISSUE TITLE
Error in Schema Definition for Post Model

### ISSUE THREAD

**Issue by sundaram08** [The-wise-ant/Blog-App#1]
The 'description' field in the Post schema should explicitly mention its type as 'String'.

Add an explicit type declaration for the description field in the Post schema, specifying it as String

**Comment by The-wise-ant** [comment]
Hi Sundaram!

Actually it's not necessary to explicit the type there. you only need it when the value is an object like in the key "title".

**Comment by sundaram08** [comment]
Hi Antonio,
Thank you for your response!

I understand your perspective regarding the explicit declaration of field types in Mongoose schemas. While it's true that Mongoose defaults to a Mixed type when the type is not explicitly specified, I believe that explicitly declaring the type for all fields can contribute to code clarity and maintainability as earlier I have faced issues because of not mentioning the type explicitly.

**Comment by sundaram08** [comment]
hereby I am closing the issue
